// Référence du schéma de la base d'entraînement (affichée dans l'app).
export const SCHEMA = [
  {
    name: 'activities',
    rows: '1 523',
    desc: "Toutes tes sorties depuis 2017 (une ligne = une activité).",
    columns: [
      ['id', 'INTEGER', 'Clé primaire'],
      ['date', 'TEXT', "Jour 'AAAA-MM-JJ'"],
      ['datetime', 'TEXT', 'Horodatage complet'],
      ['distance_km', 'REAL', 'Distance en km'],
      ['dplus_m', 'REAL', 'Dénivelé positif (m)'],
      ['hr_moy', 'INTEGER', 'FC moyenne (bpm)'],
      ['hr_max', 'INTEGER', 'FC max (bpm)'],
      ['allure_min_km', 'REAL', 'Allure (min/km)'],
      ['duree_h', 'REAL', 'Durée (heures)'],
      ['vitesse_kmh', 'REAL', 'Vitesse (km/h)'],
      ['calories', 'INTEGER', 'Calories'],
      ['is_treadmill', 'INTEGER', '1 si tapis, sinon 0'],
      ['type_id', 'INTEGER', '→ activity_types.id'],
      ['race_id', 'INTEGER', '→ races.id (NULL si pas une course)'],
      ['year', 'INTEGER', 'Année'],
      ['month', 'INTEGER', 'Mois (1-12)'],
    ],
  },
  {
    name: 'activity_types',
    rows: '3',
    desc: "Type d'activité (Route, Trail, Tapis).",
    columns: [
      ['id', 'INTEGER', 'Clé primaire'],
      ['name', 'TEXT', "'Route' | 'Trail' | 'Tapis'"],
    ],
  },
  {
    name: 'races',
    rows: '19',
    desc: 'Tes courses officielles.',
    columns: [
      ['id', 'INTEGER', 'Clé primaire'],
      ['date', 'TEXT', 'Date de la course'],
      ['name', 'TEXT', 'Nom'],
      ['distance_km', 'REAL', 'Distance officielle'],
      ['dplus_m', 'REAL', 'D+ officiel'],
      ['time_h', 'REAL', 'Temps réalisé (h)'],
      ['rank_num', 'INTEGER', 'Ton classement'],
      ['rank_tot', 'INTEGER', 'Nb de finishers'],
      ['itra', 'REAL', 'Score ITRA'],
      ['utmb_idx', 'INTEGER', 'Indice UTMB'],
      ['categorie', 'TEXT', 'Catégorie'],
      ['finished', 'INTEGER', '1 = terminée, 0 = DNF'],
    ],
  },
  {
    name: 'daily_metrics',
    rows: '1 029',
    desc: 'Métriques quotidiennes (forme, charge, récupération).',
    columns: [
      ['date', 'TEXT', 'Clé primaire (jour)'],
      ['atl', 'INTEGER', 'Fatigue court terme'],
      ['ctl', 'INTEGER', 'Forme de fond'],
      ['acwr', 'REAL', 'Ratio charge aiguë/chronique'],
      ['acwr_status', 'TEXT', 'Statut ACWR'],
      ['endurance_score', 'INTEGER', "Score d'endurance Garmin"],
      ['hill_overall', 'INTEGER', 'Score côtes global'],
      ['hill_strength', 'INTEGER', 'Score côtes force'],
      ['hill_endurance', 'INTEGER', 'Score côtes endurance'],
      ['fc_repos', 'INTEGER', 'FC au repos (bpm)'],
      ['hrv', 'INTEGER', 'Variabilité cardiaque (ms)'],
    ],
  },
];
