// Modules 11 → 14 : window functions, vues, écriture (DML) & transactions, DDL & perf.

export const M11 = {
  id: 'm11',
  navTitle: 'Window functions',
  title: 'Module 11 — Les fonctions fenêtre',
  subtitle: 'Classer, comparer à la ligne précédente, calculer des moyennes glissantes — sans perdre le détail.',
  blocks: [
    { t: 'h', text: 'Agréger sans regrouper' },
    { t: 'p', text: "`GROUP BY` **écrase** le détail : une ligne par groupe. Une **fonction fenêtre** (window function) calcule une valeur agrégée **tout en gardant chaque ligne**. La magie tient dans la clause `OVER (...)`, qui définit la « fenêtre » de lignes sur laquelle porte le calcul." },
    { t: 'h', text: 'Numéroter : ROW_NUMBER, RANK' },
    { t: 'p', text: "`ROW_NUMBER() OVER (ORDER BY ...)` attribue un numéro unique selon un ordre. `RANK()` donne le même rang aux ex æquo (et saute des numéros), `DENSE_RANK()` sans sauter." },
    { t: 'code', caption: 'Classer tes 10 plus grosses sorties en D+.', sql: "SELECT ROW_NUMBER() OVER (ORDER BY dplus_m DESC) AS rang,\n       date,\n       dplus_m\nFROM activities\nORDER BY rang\nLIMIT 10;" },
    { t: 'h', text: 'Découper en groupes : PARTITION BY' },
    { t: 'p', text: "`PARTITION BY` redémarre le calcul pour chaque groupe, **sans** fusionner les lignes. Ici : la moyenne de distance **de l'année** répétée sur chaque sortie, pour situer chaque sortie par rapport à son année." },
    { t: 'code', caption: 'Distance de la sortie vs moyenne de son année.', sql: "SELECT date,\n       distance_km,\n       ROUND(AVG(distance_km) OVER (PARTITION BY year), 1) AS moy_annee\nFROM activities\nWHERE year >= 2025\nORDER BY date\nLIMIT 20;" },
    { t: 'h', text: 'Regarder avant/après : LAG, LEAD' },
    { t: 'p', text: "`LAG(col)` récupère la valeur de la **ligne précédente** (selon l'`ORDER BY` de la fenêtre), `LEAD(col)` celle de la suivante. Parfait pour calculer un écart d'une sortie à l'autre." },
    { t: 'code', caption: 'Distance de chaque course et de la précédente.', sql: "SELECT date,\n       distance_km,\n       LAG(distance_km) OVER (ORDER BY date) AS dist_precedente\nFROM races\nORDER BY date;" },
    { t: 'h', text: 'Moyenne glissante (comme la CTL !)' },
    { t: 'p', text: "En précisant un **cadre** (`ROWS BETWEEN n PRECEDING AND CURRENT ROW`), on calcule sur une fenêtre glissante. C'est exactement l'idée derrière ta **charge chronique** : une moyenne des derniers jours qui suit la tendance." },
    { t: 'code', caption: 'Moyenne glissante de distance sur 7 sorties.', sql: "SELECT date,\n       distance_km,\n       ROUND(AVG(distance_km) OVER (\n         ORDER BY date\n         ROWS BETWEEN 6 PRECEDING AND CURRENT ROW\n       ), 1) AS moy_7\nFROM activities\nWHERE year = 2026\nORDER BY date\nLIMIT 20;" },
    { t: 'tip', text: "Les fonctions fenêtre s'évaluent **après** le `WHERE`/`GROUP BY` mais **avant** l'`ORDER BY` final. Tu ne peux donc pas les utiliser dans un `WHERE` : enveloppe la requête dans une CTE si tu veux filtrer sur un rang." },
    { t: 'note', text: "Les window functions sont standard (SQL:2003) et supportées par SQLite (≥ 3.25), PostgreSQL (de longue date) et MySQL (≥ 8.0). MySQL ≤ 5.7 ne les a pas — c'est la principale limite de portabilité à connaître." },
    {
      t: 'ex', id: 'm11-e1',
      prompt: "Classe tes **10 plus longues sorties** avec un numéro de rang `rang` (1 = la plus longue). Colonnes `rang`, `date`, `distance_km`. Trie par `rang`.",
      starter: "SELECT ROW_NUMBER() OVER (ORDER BY ...) AS rang,\n       date, distance_km\nFROM activities\nORDER BY rang\nLIMIT 10;",
      solution: "SELECT ROW_NUMBER() OVER (ORDER BY distance_km DESC) AS rang, date, distance_km FROM activities ORDER BY rang LIMIT 10;",
      ordered: true,
      hint: "`ROW_NUMBER() OVER (ORDER BY distance_km DESC)`.",
    },
    {
      t: 'ex', id: 'm11-e2',
      prompt: "Pour chaque **course** triée par date, affiche `date`, `distance_km` et la distance de la course **précédente** sous l'alias `dist_prec` (via `LAG`).",
      starter: "SELECT date, distance_km,\n       LAG(distance_km) OVER (ORDER BY ...) AS dist_prec\nFROM races\nORDER BY date;",
      solution: "SELECT date, distance_km, LAG(distance_km) OVER (ORDER BY date) AS dist_prec FROM races ORDER BY date;",
      ordered: true,
      hint: "`LAG(distance_km) OVER (ORDER BY date)` ; la première ligne aura `dist_prec` NULL.",
    },
    {
      t: 'ex', id: 'm11-e3',
      prompt: "🏁 **Défi** : sur tes sorties de 2026 (triées par date), calcule une **moyenne glissante du D+ sur 5 sorties** (`moy_dplus_5`, arrondie à l'entier). Colonnes `date`, `dplus_m`, `moy_dplus_5`. Limite 20.",
      starter: "SELECT date, dplus_m,\n       ROUND(AVG(dplus_m) OVER (\n         ORDER BY date\n         ROWS BETWEEN 4 PRECEDING AND CURRENT ROW\n       )) AS moy_dplus_5\nFROM activities\nWHERE year = 2026\nORDER BY date\nLIMIT 20;",
      solution: "SELECT date, dplus_m, ROUND(AVG(dplus_m) OVER (ORDER BY date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)) AS moy_dplus_5 FROM activities WHERE year = 2026 ORDER BY date LIMIT 20;",
      ordered: true,
      hint: "Une fenêtre de 5 lignes = `ROWS BETWEEN 4 PRECEDING AND CURRENT ROW`.",
    },
  ],
};

export const M12 = {
  id: 'm12',
  navTitle: 'Vues',
  title: 'Module 12 — Les vues (VIEW)',
  subtitle: 'Enregistrer une requête sous un nom pour la réutiliser comme une table.',
  blocks: [
    { t: 'h', text: "Qu'est-ce qu'une vue ?" },
    { t: 'p', text: "Une **vue** est une requête `SELECT` enregistrée sous un nom. Elle ne stocke **aucune donnée** : à chaque interrogation, sa requête est rejouée sur les tables réelles. On l'utilise comme une table en lecture, ce qui **cache la complexité** et évite de réécrire dix fois la même jointure." },
    { t: 'code', caption: 'Créer une vue « sorties enrichies du type ».', sql: "DROP VIEW IF EXISTS v_sorties;\nCREATE VIEW v_sorties AS\nSELECT a.date,\n       a.distance_km,\n       a.dplus_m,\n       t.name AS type\nFROM activities AS a\nJOIN activity_types AS t ON a.type_id = t.id;" },
    { t: 'p', text: "Une fois la vue créée, on l'interroge comme une table — avec `WHERE`, `ORDER BY`, agrégations, etc." },
    { t: 'code', caption: 'Interroger la vue comme une table.', sql: "SELECT type,\n       COUNT(*)           AS nb,\n       ROUND(AVG(dplus_m)) AS dplus_moy\nFROM v_sorties\nGROUP BY type\nORDER BY nb DESC;" },
    { t: 'tip', text: "`DROP VIEW IF EXISTS v_sorties;` avant le `CREATE` évite l'erreur « la vue existe déjà » si tu relances le script. On peut aussi écrire `CREATE VIEW IF NOT EXISTS`." },
    { t: 'warn', text: "Une vue reflète **toujours** l'état actuel des tables : si tu ajoutes une activité, la vue la montre aussitôt. En SQLite, une vue est en **lecture seule** (on n'y fait pas d'`INSERT`). Pour du stockage matérialisé, PostgreSQL propose les `MATERIALIZED VIEW` (pas SQLite)." },
    { t: 'note', text: "`CREATE VIEW` / `DROP VIEW` sont standard partout. `CREATE OR REPLACE VIEW` existe en PostgreSQL/MySQL mais **pas** en SQLite : d'où le `DROP ... IF EXISTS` puis `CREATE`, portable et sûr." },
    {
      t: 'ex', id: 'm12-e1',
      prompt: "Crée une vue `v_courses` = les courses **terminées** (colonnes `name`, `distance_km`, `dplus_m`, `time_h`), puis interroge-la pour afficher son contenu trié par `distance_km` décroissant. Écris le `DROP VIEW IF EXISTS` avant.",
      starter: "DROP VIEW IF EXISTS v_courses;\nCREATE VIEW v_courses AS\nSELECT name, distance_km, dplus_m, time_h\nFROM races\nWHERE ...;\nSELECT * FROM v_courses ORDER BY ...;",
      solution: "DROP VIEW IF EXISTS v_courses; CREATE VIEW v_courses AS SELECT name, distance_km, dplus_m, time_h FROM races WHERE finished = 1; SELECT * FROM v_courses ORDER BY distance_km DESC;",
      ordered: true,
      hint: "La vue filtre `WHERE finished = 1` ; la requête finale fait `SELECT * FROM v_courses ORDER BY distance_km DESC`.",
    },
    {
      t: 'ex', id: 'm12-e2',
      prompt: "🏁 **Défi** : crée une vue `v_annee` (D+ total et km total **par année**), puis interroge-la pour ne garder que les années à plus de **1500 km**. Colonnes `year`, `km_total`, `dplus_total`. Trie par `year`.",
      starter: "DROP VIEW IF EXISTS v_annee;\nCREATE VIEW v_annee AS\nSELECT year,\n       ROUND(SUM(distance_km)) AS km_total,\n       ROUND(SUM(dplus_m))     AS dplus_total\nFROM activities\nGROUP BY year;\nSELECT * FROM v_annee WHERE ... ORDER BY year;",
      solution: "DROP VIEW IF EXISTS v_annee; CREATE VIEW v_annee AS SELECT year, ROUND(SUM(distance_km)) AS km_total, ROUND(SUM(dplus_m)) AS dplus_total FROM activities GROUP BY year; SELECT * FROM v_annee WHERE km_total > 1500 ORDER BY year;",
      ordered: true,
      hint: "Après avoir créé la vue agrégée, filtre `WHERE km_total > 1500` dans la requête finale.",
    },
  ],
};

export const M13 = {
  id: 'm13',
  navTitle: 'Écrire (INSERT/UPDATE)',
  title: 'Module 13 — Modifier les données & transactions',
  subtitle: "Ajouter, modifier, supprimer des lignes — et sécuriser le tout avec des transactions.",
  blocks: [
    { t: 'h', text: 'Une base d’entraînement jetable' },
    { t: 'p', text: "Jusqu'ici on **lisait** (`SELECT`). Passons à l'**écriture**. Rassure-toi : cette base tourne **dans ton navigateur**, la vraie base UltraCoach n'est jamais touchée. Le bouton **↺ Restaurer la base** (en bas de page) annule toutes tes modifications d'un clic. Expérimente librement." },
    { t: 'h', text: 'INSERT : ajouter des lignes' },
    { t: 'p', text: "`INSERT INTO table (colonnes...) VALUES (valeurs...)` ajoute une ligne. On liste les colonnes qu'on renseigne ; les autres prennent leur valeur par défaut ou `NULL`." },
    { t: 'code', caption: 'Ajouter une sortie fictive.', sql: "INSERT INTO activities (id, date, distance_km, dplus_m, year, type_id)\nVALUES (90001, '2030-01-01', 12.5, 400, 2030, 1);\nSELECT id, date, distance_km FROM activities WHERE id = 90001;" },
    { t: 'h', text: 'UPDATE : modifier des lignes' },
    { t: 'p', text: "`UPDATE table SET colonne = valeur WHERE condition`. **Toujours** un `WHERE` : sans lui, tu modifies **toutes** les lignes de la table !" },
    { t: 'code', caption: 'Corriger le D+ d’une sortie précise.', sql: "UPDATE activities SET dplus_m = 999 WHERE id = 90001;\nSELECT id, dplus_m FROM activities WHERE id = 90001;" },
    { t: 'h', text: 'DELETE : supprimer des lignes' },
    { t: 'p', text: "`DELETE FROM table WHERE condition`. Même règle d'or : sans `WHERE`, tu vides la table entière." },
    { t: 'code', caption: 'Supprimer notre ligne de test.', sql: "DELETE FROM activities WHERE id = 90001;\nSELECT COUNT(*) AS reste FROM activities WHERE id = 90001;" },
    { t: 'h', text: 'Transactions : tout ou rien' },
    { t: 'p', text: "Une **transaction** regroupe plusieurs modifications en un bloc **atomique** : `BEGIN` ouvre, `COMMIT` valide définitivement, `ROLLBACK` **annule tout** le bloc. Si une étape échoue, on revient à l'état initial — indispensable pour ne jamais laisser la base à moitié modifiée." },
    { t: 'code', caption: 'Modifier puis tout annuler avec ROLLBACK.', sql: "BEGIN;\nUPDATE activities SET distance_km = 0 WHERE year = 2026;\n-- oups, erreur ! on annule tout :\nROLLBACK;\nSELECT COUNT(*) AS inchangees FROM activities WHERE year = 2026 AND distance_km = 0;" },
    { t: 'warn', text: "Un `UPDATE`/`DELETE` **sans `WHERE`** s'applique à toute la table, sans confirmation. En production, on entoure toujours les écritures risquées d'une transaction et on vérifie avec un `SELECT` avant de `COMMIT`. Ici, en cas de bêtise, clique sur **↺ Restaurer la base**." },
    { t: 'note', text: "`INSERT`, `UPDATE`, `DELETE` sont standard. Les transactions aussi (`BEGIN`/`COMMIT`/`ROLLBACK`), avec de petites variantes de mot-clé (`BEGIN` vs `START TRANSACTION` en MySQL). SQLite est transactionnel par défaut : chaque instruction isolée est déjà une mini-transaction auto-validée." },
    { t: 'tip', text: "Astuce pour ces exercices : si un `Vérifier` te renvoie un résultat étrange, clique sur **↺ Restaurer la base** puis réessaie — tu repars d'une base propre." },
    {
      t: 'ex', id: 'm13-e1',
      prompt: "Mets le `dplus_m` de l'activité `id = 1` à **500**, puis affiche `id, dplus_m` de cette activité. (Un `UPDATE` puis un `SELECT`.)",
      starter: "UPDATE activities SET dplus_m = 500 WHERE id = 1;\nSELECT id, dplus_m FROM activities WHERE id = 1;",
      solution: "UPDATE activities SET dplus_m = 500 WHERE id = 1; SELECT id, dplus_m FROM activities WHERE id = 1;",
      hint: "`UPDATE activities SET dplus_m = 500 WHERE id = 1;` puis un `SELECT` filtré sur `id = 1`.",
    },
    {
      t: 'ex', id: 'm13-e2',
      prompt: "Supprime toutes les activités de **moins de 1 km** (`distance_km < 1`), puis affiche le **nombre d'activités restantes** sous l'alias `nb`.",
      starter: "DELETE FROM activities WHERE ...;\nSELECT COUNT(*) AS nb FROM activities;",
      solution: "DELETE FROM activities WHERE distance_km < 1; SELECT COUNT(*) AS nb FROM activities;",
      hint: "`DELETE FROM activities WHERE distance_km < 1;` puis `SELECT COUNT(*) AS nb FROM activities;`. (Relancer le DELETE ne supprime rien de plus : le compte est stable.)",
    },
    {
      t: 'ex', id: 'm13-e3',
      prompt: "🏁 **Défi** : ajoute une activité fictive `id = 90002` (date `'2030-06-01'`, `distance_km = 20`, `dplus_m = 800`, `year = 2030`, `type_id = 2`) **seulement si elle n'existe pas déjà**, puis affiche `id, distance_km, dplus_m` de cette activité.",
      starter: "INSERT INTO activities (id, date, distance_km, dplus_m, year, type_id)\nSELECT 90002, '2030-06-01', 20, 800, 2030, 2\nWHERE NOT EXISTS (SELECT 1 FROM activities WHERE id = 90002);\nSELECT id, distance_km, dplus_m FROM activities WHERE id = 90002;",
      solution: "INSERT INTO activities (id, date, distance_km, dplus_m, year, type_id) SELECT 90002, '2030-06-01', 20, 800, 2030, 2 WHERE NOT EXISTS (SELECT 1 FROM activities WHERE id = 90002); SELECT id, distance_km, dplus_m FROM activities WHERE id = 90002;",
      hint: "La forme `INSERT INTO ... SELECT ... WHERE NOT EXISTS (...)` n'insère que si la ligne manque — on peut la rejouer sans créer de doublon.",
    },
  ],
};

export const M14 = {
  id: 'm14',
  navTitle: 'Perf, DDL & index',
  title: 'Module 14 — Créer des tables, indexer, optimiser',
  subtitle: 'Définir des structures (DDL), accélérer les requêtes avec des index, lire un plan d’exécution.',
  blocks: [
    { t: 'h', text: 'DDL : définir la structure' },
    { t: 'p', text: "Le **DDL** (Data Definition Language) crée et modifie la **structure** : `CREATE TABLE`, `ALTER TABLE`, `DROP TABLE`. On y déclare les colonnes, leurs **types** (`INTEGER`, `REAL`, `TEXT`) et des **contraintes** (`PRIMARY KEY`, `NOT NULL`, `DEFAULT`, `FOREIGN KEY`)." },
    { t: 'code', caption: 'Créer une petite table de notes de séance.', sql: "DROP TABLE IF EXISTS notes;\nCREATE TABLE notes (\n  id      INTEGER PRIMARY KEY,\n  date    TEXT NOT NULL,\n  ressenti INTEGER,\n  commentaire TEXT DEFAULT ''\n);\nINSERT INTO notes (id, date, ressenti, commentaire)\nVALUES (1, '2026-08-01', 8, 'jambes légères');\nSELECT * FROM notes;" },
    { t: 'p', text: "`PRIMARY KEY` identifie chaque ligne de façon unique. `NOT NULL` interdit l'absence de valeur. `DEFAULT` fournit une valeur si on n'en donne pas." },
    { t: 'h', text: 'Les index : accélérer les recherches' },
    { t: 'p', text: "Un **index** est une structure annexe qui accélère les recherches et les tris sur une colonne, un peu comme l'index d'un livre évite de tout parcourir. On l'ajoute sur les colonnes souvent filtrées (`WHERE`) ou jointes (`ON`)." },
    { t: 'code', caption: 'Indexer la colonne year, puis vérifier sa présence.', sql: "CREATE INDEX IF NOT EXISTS idx_activities_year ON activities(year);\nSELECT name, tbl_name\nFROM sqlite_master\nWHERE type = 'index' AND name = 'idx_activities_year';" },
    { t: 'h', text: 'Lire un plan d’exécution' },
    { t: 'p', text: "`EXPLAIN QUERY PLAN` (en SQLite) montre **comment** le moteur compte exécuter une requête : parcours complet de table (`SCAN`) ou utilisation d'un index (`SEARCH ... USING INDEX`). C'est l'outil pour comprendre pourquoi une requête est lente." },
    { t: 'code', caption: 'Comparer le plan avec l’index créé ci-dessus.', sql: "EXPLAIN QUERY PLAN\nSELECT * FROM activities WHERE year = 2026;" },
    { t: 'tip', text: "Un index accélère la **lecture** mais ralentit légèrement les **écritures** (il faut le tenir à jour) et occupe de l'espace. On indexe donc les colonnes vraiment sollicitées, pas tout. Les `PRIMARY KEY` sont déjà indexées automatiquement." },
    { t: 'warn', text: "`DROP TABLE` supprime la table **et toutes ses données**, définitivement. Le `IF EXISTS` évite l'erreur si elle n'existe pas, mais ne protège pas des données perdues. À manier avec prudence hors bac à sable." },
    { t: 'note', text: "`CREATE TABLE`, `CREATE INDEX`, `DROP` sont standard. Les **types** diffèrent : SQLite est souple (typage dynamique, `INTEGER`/`REAL`/`TEXT`), là où PostgreSQL/MySQL sont stricts (`VARCHAR(n)`, `SERIAL`, `AUTO_INCREMENT`…). `EXPLAIN QUERY PLAN` est propre à SQLite ; PostgreSQL/MySQL utilisent `EXPLAIN` (et `EXPLAIN ANALYZE`)." },
    {
      t: 'ex', id: 'm14-e1',
      prompt: "Crée une table `objectifs` avec `id INTEGER PRIMARY KEY`, `libelle TEXT NOT NULL`, `km_cible REAL`. Insère la ligne `(1, 'UTMB', 170)`. Puis affiche tout le contenu. Mets un `DROP TABLE IF EXISTS objectifs;` en tête.",
      starter: "DROP TABLE IF EXISTS objectifs;\nCREATE TABLE objectifs (\n  id INTEGER PRIMARY KEY,\n  libelle TEXT NOT NULL,\n  km_cible REAL\n);\nINSERT INTO objectifs (id, libelle, km_cible) VALUES (1, 'UTMB', 170);\nSELECT * FROM objectifs;",
      solution: "DROP TABLE IF EXISTS objectifs; CREATE TABLE objectifs (id INTEGER PRIMARY KEY, libelle TEXT NOT NULL, km_cible REAL); INSERT INTO objectifs (id, libelle, km_cible) VALUES (1, 'UTMB', 170); SELECT * FROM objectifs;",
      hint: "Ordre : `DROP TABLE IF EXISTS`, puis `CREATE TABLE (...)`, puis `INSERT`, puis `SELECT * FROM objectifs;`.",
    },
    {
      t: 'ex', id: 'm14-e2',
      prompt: "🏁 **Défi** : crée un index `idx_races_dplus` sur la colonne `dplus_m` de `races` (avec `IF NOT EXISTS`), puis vérifie sa création en affichant `name` depuis `sqlite_master` (type = 'index', name = 'idx_races_dplus').",
      starter: "CREATE INDEX IF NOT EXISTS idx_races_dplus ON races(...);\nSELECT name FROM sqlite_master\nWHERE type = 'index' AND name = 'idx_races_dplus';",
      solution: "CREATE INDEX IF NOT EXISTS idx_races_dplus ON races(dplus_m); SELECT name FROM sqlite_master WHERE type = 'index' AND name = 'idx_races_dplus';",
      hint: "`CREATE INDEX IF NOT EXISTS idx_races_dplus ON races(dplus_m);` puis interroge `sqlite_master`.",
    },
  ],
};
