// Modules 00 → 06 : des fondations à GROUP BY.

export const M00 = {
  id: 'm00',
  navTitle: 'Fondations',
  title: 'Module 0 — Les fondations',
  subtitle: "Comprendre ce qu'est une base de données relationnelle avant d'écrire la moindre requête.",
  blocks: [
    { t: 'h', text: "C'est quoi une base de données ?" },
    { t: 'p', text: "Une **base de données relationnelle** organise l'information en **tables**. Une table, c'est comme une feuille de tableur : des **colonnes** (les champs, ex. `distance_km`) et des **lignes** (les enregistrements, ex. une sortie précise)." },
    { t: 'p', text: "Ta base d'entraînement contient 4 tables : `activities` (tes 1 523 sorties), `races` (tes 19 courses), `activity_types` (Route/Trail/Tapis) et `daily_metrics` (ta forme jour par jour). Ouvre l'onglet **📐 Schéma de la base** à gauche : ce sera ta carte tout au long du parcours." },
    { t: 'h', text: 'Le langage SQL' },
    { t: 'p', text: "**SQL** (Structured Query Language) est le langage pour *interroger* et *manipuler* ces tables. Une instruction SQL s'appelle une **requête**. La plus courante commence par `SELECT` : elle **lit** des données sans rien modifier." },
    { t: 'p', text: "Anatomie d'une requête de lecture : on choisit **quelles colonnes** (`SELECT`), **dans quelle table** (`FROM`), avec quels **filtres** (`WHERE`), dans quel **ordre** (`ORDER BY`). On verra tout ça, une brique à la fois." },
    { t: 'code', caption: "Ta toute première requête : lire 5 lignes de la table des activités.", sql: 'SELECT *\nFROM activities\nLIMIT 5;' },
    { t: 'p', text: "L'astérisque `*` veut dire « toutes les colonnes ». `LIMIT 5` n'en garde que 5 (pratique sur 1 523 lignes !). Le `;` final termine la requête. Clique sur **▶ Essayer dans le bac à sable** ci-dessus pour l'exécuter." },
    { t: 'tip', text: "Le SQL n'est **pas sensible à la casse** pour les mots-clés : `SELECT`, `select`, `Select` sont identiques. La convention est de les écrire en MAJUSCULES pour la lisibilité." },
    { t: 'note', text: "Ces notions (tables, lignes, colonnes, `SELECT ... FROM`) sont **identiques** dans SQLite, PostgreSQL, MySQL, SQL Server… Le socle que tu apprends ici est universel." },
    {
      t: 'ex', id: 'm00-e1',
      prompt: "À toi : affiche **les 3 premières lignes** de la table `races` (toutes les colonnes).",
      starter: 'SELECT ...\nFROM ...\nLIMIT ...;',
      solution: 'SELECT * FROM races LIMIT 3;',
      hint: "Reprends la structure `SELECT * FROM <table> LIMIT <n>;` en remplaçant la table par `races` et le nombre par 3.",
    },
    {
      t: 'ex', id: 'm00-e2',
      prompt: "Affiche les **10 premières lignes** de la table `daily_metrics`.",
      starter: 'SELECT * FROM daily_metrics LIMIT 10;',
      solution: 'SELECT * FROM daily_metrics LIMIT 10;',
      hint: "Même schéma, table `daily_metrics`, limite 10.",
    },
  ],
};

export const M01 = {
  id: 'm01',
  navTitle: 'SELECT',
  title: 'Module 1 — SELECT : choisir ses colonnes',
  subtitle: 'Sélectionner précisément les colonnes, les renommer, éliminer les doublons.',
  blocks: [
    { t: 'h', text: 'Choisir des colonnes précises' },
    { t: 'p', text: "Plutôt que `*`, on liste les colonnes voulues, séparées par des virgules. C'est plus clair et plus rapide." },
    { t: 'code', caption: 'Uniquement la date, la distance et le dénivelé de chaque sortie.', sql: 'SELECT date, distance_km, dplus_m\nFROM activities\nLIMIT 10;' },
    { t: 'h', text: 'Renommer avec un alias (AS)' },
    { t: 'p', text: "Le mot-clé `AS` donne un **alias** (nom d'affichage) à une colonne. Utile pour rendre le résultat lisible ou nommer un calcul." },
    { t: 'code', caption: 'Renommer les colonnes en français lisible.', sql: "SELECT date AS jour,\n       distance_km AS km,\n       dplus_m AS denivele\nFROM activities\nLIMIT 10;" },
    { t: 'tip', text: "`AS` est **optionnel** : `distance_km km` marche aussi. Mais l'écrire est plus lisible. Si l'alias contient un espace, entoure-le de guillemets doubles : `distance_km AS \"distance (km)\"`." },
    { t: 'h', text: 'Calculer dans le SELECT' },
    { t: 'p', text: "On peut faire des calculs directement : par exemple le dénivelé par kilomètre, un bon indicateur de « verticalité » d'une sortie." },
    { t: 'code', caption: 'Un calcul avec alias.', sql: 'SELECT date,\n       distance_km,\n       dplus_m,\n       dplus_m / distance_km AS d_par_km\nFROM activities\nLIMIT 10;' },
    { t: 'h', text: 'Éliminer les doublons : DISTINCT' },
    { t: 'p', text: "`DISTINCT` supprime les lignes en double du résultat. Idéal pour lister les valeurs *uniques* d'une colonne." },
    { t: 'code', caption: 'Toutes les années où tu as une activité (sans répétition).', sql: 'SELECT DISTINCT year\nFROM activities\nORDER BY year;' },
    { t: 'note', text: "SQLite, PostgreSQL et MySQL gèrent tous `SELECT`, `AS`, `DISTINCT` de façon identique. La division `/` : attention, sur des entiers, PostgreSQL fait une division **entière** (5/2 = 2). Ici les colonnes sont des réels (`REAL`), donc pas de souci." },
    {
      t: 'ex', id: 'm01-e1',
      prompt: "Affiche uniquement les colonnes `date`, `hr_moy` et `hr_max` des activités (limite à 15 lignes).",
      starter: 'SELECT ...\nFROM activities\nLIMIT 15;',
      solution: 'SELECT date, hr_moy, hr_max FROM activities LIMIT 15;',
      hint: 'Liste les trois colonnes séparées par des virgules après `SELECT`.',
    },
    {
      t: 'ex', id: 'm01-e2',
      prompt: "Affiche `name` et `dplus_m` de `races`, mais renomme `dplus_m` en `denivele`. (Toutes les lignes.)",
      starter: 'SELECT ... FROM races;',
      solution: 'SELECT name, dplus_m AS denivele FROM races;',
      hint: 'Utilise `dplus_m AS denivele`.',
    },
    {
      t: 'ex', id: 'm01-e3',
      prompt: "Liste les **types d'activité distincts** présents dans la colonne `type_id` de `activities`.",
      starter: 'SELECT DISTINCT ... FROM activities;',
      solution: 'SELECT DISTINCT type_id FROM activities;',
      hint: '`SELECT DISTINCT type_id FROM activities;`',
    },
    {
      t: 'ex', id: 'm01-e4',
      prompt: "🏁 **Défi** : pour chaque activité, affiche la `date` et sa **vitesse recalculée** en km/h sous l'alias `vitesse_calc`, sachant que vitesse = `distance_km / duree_h`. Limite à 10.",
      starter: 'SELECT date,\n       ...\nFROM activities\nLIMIT 10;',
      solution: 'SELECT date, distance_km / duree_h AS vitesse_calc FROM activities LIMIT 10;',
      hint: 'Divise `distance_km` par `duree_h` et donne-lui un alias avec `AS`.',
    },
  ],
};

export const M02 = {
  id: 'm02',
  navTitle: 'WHERE (filtrer)',
  title: 'Module 2 — WHERE : filtrer les lignes',
  subtitle: 'Ne garder que les lignes qui remplissent une condition.',
  blocks: [
    { t: 'h', text: 'La clause WHERE' },
    { t: 'p', text: "`WHERE` filtre les lignes selon une condition. Elle se place **après** `FROM`. Seules les lignes où la condition est **vraie** sont renvoyées." },
    { t: 'code', caption: 'Uniquement les sorties de plus de 30 km.', sql: 'SELECT date, distance_km, dplus_m\nFROM activities\nWHERE distance_km > 30;' },
    { t: 'p', text: "Opérateurs de comparaison : `=` (égal), `<>` ou `!=` (différent), `<`, `<=`, `>`, `>=`." },
    { t: 'h', text: 'Combiner : AND, OR, NOT' },
    { t: 'p', text: "On enchaîne plusieurs conditions avec `AND` (les deux vraies), `OR` (au moins une), `NOT` (négation). Les parenthèses clarifient la priorité." },
    { t: 'code', caption: 'Sorties longues ET très vallonnées.', sql: 'SELECT date, distance_km, dplus_m\nFROM activities\nWHERE distance_km > 40 AND dplus_m > 2000;' },
    { t: 'h', text: 'Intervalles et listes : BETWEEN, IN' },
    { t: 'p', text: "`BETWEEN a AND b` teste un intervalle (bornes incluses). `IN (...)` teste l'appartenance à une liste." },
    { t: 'code', caption: 'Sorties dont la FC moyenne est dans une zone donnée.', sql: 'SELECT date, distance_km, hr_moy\nFROM activities\nWHERE hr_moy BETWEEN 140 AND 150;' },
    { t: 'code', caption: 'Activités de type Trail (2) ou Tapis (3).', sql: 'SELECT date, distance_km, type_id\nFROM activities\nWHERE type_id IN (2, 3)\nLIMIT 20;' },
    { t: 'h', text: 'Texte : LIKE' },
    { t: 'p', text: "`LIKE` filtre du texte avec des jokers : `%` = n'importe quelle suite de caractères, `_` = un seul caractère." },
    { t: 'code', caption: "Courses dont le nom contient « Trail ».", sql: "SELECT name, date\nFROM races\nWHERE name LIKE '%Trail%';" },
    { t: 'h', text: 'Les valeurs NULL' },
    { t: 'p', text: "`NULL` = **absence de valeur** (inconnue). On ne teste **jamais** `= NULL` : on écrit `IS NULL` ou `IS NOT NULL`. Beaucoup de tes vieilles sorties n'ont pas de FC enregistrée (`hr_moy IS NULL`)." },
    { t: 'code', caption: 'Sorties sans donnée de fréquence cardiaque.', sql: 'SELECT date, distance_km\nFROM activities\nWHERE hr_moy IS NULL\nLIMIT 15;' },
    { t: 'warn', text: "Une comparaison avec `NULL` (ex. `hr_moy > 140`) renvoie « inconnu », donc la ligne est **exclue**. C'est normal, mais souviens-t'en quand un filtre semble « perdre » des lignes." },
    { t: 'note', text: "`LIKE` est **insensible à la casse** en SQLite et MySQL par défaut, mais **sensible** en PostgreSQL (où l'on utilise `ILIKE` pour ignorer la casse). `BETWEEN`, `IN`, `IS NULL` sont identiques partout." },
    {
      t: 'ex', id: 'm02-e1',
      prompt: "Affiche `date`, `distance_km`, `dplus_m` des sorties de **plus de 3000 m de D+**.",
      starter: 'SELECT date, distance_km, dplus_m\nFROM activities\nWHERE ...;',
      solution: 'SELECT date, distance_km, dplus_m FROM activities WHERE dplus_m > 3000;',
      hint: 'Condition : `dplus_m > 3000`.',
    },
    {
      t: 'ex', id: 'm02-e2',
      prompt: "Affiche les courses **terminées** (`finished = 1`) de plus de 70 km : colonnes `name`, `distance_km`, `time_h`.",
      starter: 'SELECT name, distance_km, time_h\nFROM races\nWHERE ...;',
      solution: 'SELECT name, distance_km, time_h FROM races WHERE finished = 1 AND distance_km > 70;',
      hint: 'Deux conditions reliées par `AND` : `finished = 1` et `distance_km > 70`.',
    },
    {
      t: 'ex', id: 'm02-e3',
      prompt: "Affiche `date` et `distance_km` des sorties **tapis** (`is_treadmill = 1`) de l'année 2026.",
      starter: 'SELECT date, distance_km\nFROM activities\nWHERE ...;',
      solution: 'SELECT date, distance_km FROM activities WHERE is_treadmill = 1 AND year = 2026;',
      hint: '`is_treadmill = 1 AND year = 2026`.',
    },
    {
      t: 'ex', id: 'm02-e4',
      prompt: "Trouve les courses dont le nom contient « km » : colonnes `name`, `date`.",
      starter: "SELECT name, date FROM races WHERE name LIKE ...;",
      solution: "SELECT name, date FROM races WHERE name LIKE '%km%';",
      hint: "Motif `'%km%'` avec `LIKE`.",
    },
    {
      t: 'ex', id: 'm02-e5',
      prompt: "🏁 **Défi** : sorties « qualité » = distance entre 8 et 15 km **avec** une FC moyenne renseignée (non NULL) **et** un D+ d'au moins 500 m. Affiche `date`, `distance_km`, `dplus_m`, `hr_moy`.",
      starter: 'SELECT date, distance_km, dplus_m, hr_moy\nFROM activities\nWHERE ...;',
      solution: 'SELECT date, distance_km, dplus_m, hr_moy FROM activities WHERE distance_km BETWEEN 8 AND 15 AND hr_moy IS NOT NULL AND dplus_m >= 500;',
      hint: 'Combine `BETWEEN 8 AND 15`, `hr_moy IS NOT NULL` et `dplus_m >= 500` avec des `AND`.',
    },
  ],
};

export const M03 = {
  id: 'm03',
  navTitle: 'ORDER BY (trier)',
  title: 'Module 3 — ORDER BY : trier les résultats',
  subtitle: 'Classer les lignes, dans un sens ou dans l’autre, sur un ou plusieurs critères.',
  blocks: [
    { t: 'h', text: 'Trier avec ORDER BY' },
    { t: 'p', text: "`ORDER BY` classe les lignes selon une colonne. Par défaut c'est **croissant** (`ASC`). Ajoute `DESC` pour **décroissant**. La clause se place à la fin, après `WHERE`." },
    { t: 'code', caption: 'Tes plus grosses sorties en dénivelé, en premier.', sql: 'SELECT date, distance_km, dplus_m\nFROM activities\nORDER BY dplus_m DESC\nLIMIT 10;' },
    { t: 'h', text: 'Trier sur plusieurs colonnes' },
    { t: 'p', text: "On peut trier par plusieurs critères successifs : d'abord par le premier, puis en cas d'égalité par le second, etc." },
    { t: 'code', caption: "D'abord par année (récente en haut), puis par distance décroissante.", sql: 'SELECT date, year, distance_km\nFROM activities\nORDER BY year DESC, distance_km DESC\nLIMIT 15;' },
    { t: 'tip', text: "Combiné à `LIMIT`, `ORDER BY` répond aux questions « top N » : *ma sortie la plus longue*, *mes 5 courses les plus rapides*… Trie dans le bon sens puis limite." },
    { t: 'p', text: "On peut trier sur un **alias** ou une **expression**. Ex. `ORDER BY dplus_m / distance_km DESC` classe par verticalité." },
    { t: 'note', text: "Le placement des `NULL` dans le tri **diffère** : SQLite et PostgreSQL mettent les `NULL` en premier en tri croissant ; MySQL aussi. PostgreSQL permet `ORDER BY col DESC NULLS LAST` pour choisir — pas SQLite. Filtre les `NULL` avec `WHERE` si l'ordre t'importe." },
    {
      t: 'ex', id: 'm03-e1',
      prompt: "Affiche les **10 sorties les plus longues** (`date`, `distance_km`), la plus longue en premier.",
      starter: 'SELECT date, distance_km\nFROM activities\nORDER BY ...\nLIMIT 10;',
      solution: 'SELECT date, distance_km FROM activities ORDER BY distance_km DESC LIMIT 10;',
      ordered: true,
      hint: '`ORDER BY distance_km DESC` puis `LIMIT 10`.',
    },
    {
      t: 'ex', id: 'm03-e2',
      prompt: "Classe les courses **terminées** de la plus rapide à la plus lente (`time_h` croissant) : `name`, `distance_km`, `time_h`.",
      starter: 'SELECT name, distance_km, time_h\nFROM races\nWHERE finished = 1\nORDER BY ...;',
      solution: 'SELECT name, distance_km, time_h FROM races WHERE finished = 1 ORDER BY time_h ASC;',
      ordered: true,
      hint: '`ORDER BY time_h ASC` (ASC est optionnel).',
    },
    {
      t: 'ex', id: 'm03-e3',
      prompt: "🏁 **Défi** : parmi les sorties de 2026 avec FC renseignée, classe par **verticalité** (`dplus_m / distance_km`) décroissante. Affiche `date`, `distance_km`, `dplus_m`. Limite 8.",
      starter: 'SELECT date, distance_km, dplus_m\nFROM activities\nWHERE year = 2026 AND hr_moy IS NOT NULL\nORDER BY ...\nLIMIT 8;',
      solution: 'SELECT date, distance_km, dplus_m FROM activities WHERE year = 2026 AND hr_moy IS NOT NULL ORDER BY dplus_m / distance_km DESC LIMIT 8;',
      ordered: true,
      hint: 'Tu peux trier directement sur une expression : `ORDER BY dplus_m / distance_km DESC`.',
    },
  ],
};

export const M04 = {
  id: 'm04',
  navTitle: 'Fonctions',
  title: 'Module 4 — Les fonctions',
  subtitle: 'Transformer des valeurs : nombres, texte et surtout dates.',
  blocks: [
    { t: 'h', text: 'Fonctions numériques' },
    { t: 'p', text: "Elles transforment un nombre. Les plus utiles : `ROUND(x, n)` arrondit à n décimales, `ABS(x)` valeur absolue, `MIN(a,b)` / `MAX(a,b)` sur des valeurs." },
    { t: 'code', caption: 'Arrondir la verticalité à 1 décimale.', sql: 'SELECT date,\n       distance_km,\n       dplus_m,\n       ROUND(dplus_m / distance_km, 1) AS d_par_km\nFROM activities\nWHERE distance_km > 20\nLIMIT 10;' },
    { t: 'h', text: 'Fonctions texte' },
    { t: 'p', text: "`UPPER` / `LOWER` changent la casse, `LENGTH` donne la longueur, et la **concaténation** colle des chaînes. En SQL standard et SQLite/PostgreSQL, l'opérateur de concaténation est `||`." },
    { t: 'code', caption: 'Composer une étiquette lisible par course.', sql: "SELECT name || ' (' || distance_km || ' km)' AS libelle\nFROM races\nORDER BY distance_km DESC\nLIMIT 8;" },
    { t: 'h', text: 'Les dates' },
    { t: 'p', text: "Ici les dates sont stockées en **texte** au format `AAAA-MM-JJ` (le format ISO, qui se trie correctement comme du texte). En SQLite, on les décortique avec `strftime(format, date)` : `%Y` = année, `%m` = mois, `%d` = jour, `%w` = jour de semaine (0=dimanche)." },
    { t: 'code', caption: 'Extraire année et mois depuis la date texte.', sql: "SELECT date,\n       strftime('%Y', date) AS annee,\n       strftime('%m', date) AS mois\nFROM activities\nLIMIT 10;" },
    { t: 'tip', text: "Comme le format est ISO (`AAAA-MM-JJ`), tu peux comparer les dates comme du texte : `WHERE date >= '2026-01-01'` fonctionne parfaitement, sans fonction." },
    { t: 'note', text: "**Grosse différence entre moteurs sur les dates !** `strftime` est propre à SQLite. PostgreSQL utilise `EXTRACT(YEAR FROM date)` et `TO_CHAR(date, 'YYYY')`. MySQL utilise `YEAR(date)`, `MONTH(date)`, `DATE_FORMAT(...)`. La concaténation aussi diffère : `||` (SQLite/PostgreSQL) vs `CONCAT(...)` (MySQL)." },
    {
      t: 'ex', id: 'm04-e1',
      prompt: "Affiche `date`, `distance_km` et la distance **arrondie à l'entier** sous l'alias `km_arrondi` (10 lignes).",
      starter: 'SELECT date, distance_km, ROUND(...) AS km_arrondi\nFROM activities\nLIMIT 10;',
      solution: 'SELECT date, distance_km, ROUND(distance_km, 0) AS km_arrondi FROM activities LIMIT 10;',
      hint: '`ROUND(distance_km, 0)`.',
    },
    {
      t: 'ex', id: 'm04-e2',
      prompt: "Pour chaque course, compose `name` suivi de son temps, ex. « Sibérie 52km — 5.763 h », sous l'alias `resume`. (Toutes les lignes, courses terminées.)",
      starter: "SELECT name || ... AS resume\nFROM races\nWHERE finished = 1;",
      solution: "SELECT name || ' — ' || time_h || ' h' AS resume FROM races WHERE finished = 1;",
      hint: "Concatène avec `||` : `name || ' — ' || time_h || ' h'`.",
    },
    {
      t: 'ex', id: 'm04-e3',
      prompt: "🏁 **Défi** : liste les activités du **mois de juillet** (tous les ans confondus) avec `date` et `distance_km`. Utilise `strftime` sur la colonne `date`.",
      starter: "SELECT date, distance_km\nFROM activities\nWHERE strftime('%m', date) = ...;",
      solution: "SELECT date, distance_km FROM activities WHERE strftime('%m', date) = '07';",
      hint: "Le mois de juillet est `'07'` (avec le zéro). `strftime('%m', date) = '07'`.",
    },
  ],
};

export const M05 = {
  id: 'm05',
  navTitle: 'Agrégations',
  title: 'Module 5 — Les agrégations',
  subtitle: 'Résumer plusieurs lignes en une seule valeur : compter, sommer, moyenner.',
  blocks: [
    { t: 'h', text: 'Les fonctions d’agrégation' },
    { t: 'p', text: "Une **fonction d'agrégation** condense un ensemble de lignes en **une seule valeur**. Les cinq essentielles : `COUNT` (compter), `SUM` (somme), `AVG` (moyenne), `MIN` (minimum), `MAX` (maximum)." },
    { t: 'code', caption: 'Combien de sorties au total ?', sql: 'SELECT COUNT(*) AS nb_sorties\nFROM activities;' },
    { t: 'p', text: "`COUNT(*)` compte les lignes. `COUNT(colonne)` compte les lignes où la colonne **n'est pas NULL** — utile pour savoir combien de sorties ont une FC enregistrée." },
    { t: 'code', caption: 'Total et moyennes sur toutes tes sorties.', sql: 'SELECT COUNT(*)            AS nb,\n       ROUND(SUM(distance_km))    AS km_total,\n       ROUND(SUM(dplus_m))        AS dplus_total,\n       ROUND(AVG(distance_km), 1) AS km_moyen\nFROM activities;' },
    { t: 'h', text: 'Combiner avec WHERE' },
    { t: 'p', text: "Le `WHERE` filtre **avant** l'agrégation : on résume seulement les lignes retenues." },
    { t: 'code', caption: 'Ton dénivelé total cumulé en 2026.', sql: 'SELECT ROUND(SUM(dplus_m)) AS dplus_2026,\n       COUNT(*)          AS nb_sorties\nFROM activities\nWHERE year = 2026;' },
    { t: 'tip', text: "`AVG` ignore automatiquement les `NULL` (il ne les compte pas au dénominateur). Donc `AVG(hr_moy)` te donne la FC moyenne réelle sur les sorties où elle existe." },
    { t: 'note', text: "`COUNT`, `SUM`, `AVG`, `MIN`, `MAX` sont **standard** partout. Petite nuance : `AVG` sur une colonne entière renvoie un réel en SQLite/PostgreSQL. `COUNT(DISTINCT col)` (compter les valeurs uniques) marche aussi dans les trois moteurs." },
    {
      t: 'ex', id: 'm05-e1',
      prompt: "Compte le nombre de courses **terminées** (`finished = 1`) sous l'alias `nb_finish`.",
      starter: 'SELECT COUNT(*) AS nb_finish\nFROM races\nWHERE ...;',
      solution: 'SELECT COUNT(*) AS nb_finish FROM races WHERE finished = 1;',
      hint: '`COUNT(*)` avec `WHERE finished = 1`.',
    },
    {
      t: 'ex', id: 'm05-e2',
      prompt: "Quelle est ta **distance maximale** et ta **FC moyenne** sur l'ensemble des sorties ? Alias `dist_max` et `fc_moyenne` (arrondie à l'entier).",
      starter: 'SELECT MAX(...) AS dist_max,\n       ROUND(AVG(...)) AS fc_moyenne\nFROM activities;',
      solution: 'SELECT MAX(distance_km) AS dist_max, ROUND(AVG(hr_moy)) AS fc_moyenne FROM activities;',
      hint: '`MAX(distance_km)` et `ROUND(AVG(hr_moy))`.',
    },
    {
      t: 'ex', id: 'm05-e3',
      prompt: "🏁 **Défi** : sur tes sorties **trail** (`type_id = 2`), donne le nombre de sorties (`nb`), le D+ total (`dplus_total`, arrondi) et le D+ moyen par sortie (`dplus_moyen`, arrondi).",
      starter: 'SELECT COUNT(*) AS nb,\n       ROUND(SUM(dplus_m)) AS dplus_total,\n       ROUND(AVG(dplus_m)) AS dplus_moyen\nFROM activities\nWHERE ...;',
      solution: 'SELECT COUNT(*) AS nb, ROUND(SUM(dplus_m)) AS dplus_total, ROUND(AVG(dplus_m)) AS dplus_moyen FROM activities WHERE type_id = 2;',
      hint: 'Filtre `type_id = 2` et applique `COUNT`, `SUM`, `AVG`.',
    },
  ],
};

export const M06 = {
  id: 'm06',
  navTitle: 'GROUP BY',
  title: 'Module 6 — GROUP BY & HAVING',
  subtitle: 'Agréger par catégorie : une valeur résumée pour chaque groupe.',
  blocks: [
    { t: 'h', text: 'Regrouper avec GROUP BY' },
    { t: 'p', text: "Jusqu'ici, une agrégation renvoyait **une** valeur pour toute la table. `GROUP BY` la calcule **par groupe** : une ligne de résultat par valeur distincte de la colonne de regroupement." },
    { t: 'code', caption: 'Nombre de sorties et km cumulés PAR année.', sql: 'SELECT year,\n       COUNT(*)               AS nb,\n       ROUND(SUM(distance_km)) AS km\nFROM activities\nGROUP BY year\nORDER BY year;' },
    { t: 'p', text: "Règle d'or : dans le `SELECT`, chaque colonne est **soit** dans le `GROUP BY`, **soit** dans une fonction d'agrégation. Ici `year` est groupé, `COUNT`/`SUM` sont agrégés." },
    { t: 'code', caption: 'Volume par type d’activité (via type_id).', sql: 'SELECT type_id,\n       COUNT(*)               AS nb,\n       ROUND(SUM(dplus_m))     AS dplus_total\nFROM activities\nGROUP BY type_id\nORDER BY dplus_total DESC;' },
    { t: 'h', text: 'Filtrer les groupes : HAVING' },
    { t: 'p', text: "`WHERE` filtre les **lignes** (avant regroupement). Pour filtrer les **groupes** (après agrégation), on utilise `HAVING`. Exemple : ne garder que les années où tu as couru plus de 1000 km." },
    { t: 'code', caption: 'Années à gros volume (> 2000 km).', sql: 'SELECT year,\n       ROUND(SUM(distance_km)) AS km\nFROM activities\nGROUP BY year\nHAVING SUM(distance_km) > 2000\nORDER BY km DESC;' },
    { t: 'warn', text: "Ordre logique d'exécution : `FROM` → `WHERE` → `GROUP BY` → `HAVING` → `SELECT` → `ORDER BY`. C'est pour ça qu'on ne peut pas utiliser un alias du `SELECT` dans le `WHERE` (il n'existe pas encore), mais souvent oui dans le `ORDER BY`." },
    { t: 'note', text: "`GROUP BY` / `HAVING` sont standard. Nuance : MySQL et SQLite tolèrent des colonnes non agrégées « hors GROUP BY » (comportement risqué) ; PostgreSQL l'**interdit** strictement. Bonne habitude : respecte la règle d'or, ton SQL sera portable." },
    {
      t: 'ex', id: 'm06-e1',
      prompt: "Compte le nombre de sorties **par type** (`type_id`) : colonnes `type_id` et `nb`.",
      starter: 'SELECT type_id, COUNT(*) AS nb\nFROM activities\nGROUP BY ...;',
      solution: 'SELECT type_id, COUNT(*) AS nb FROM activities GROUP BY type_id;',
      hint: '`GROUP BY type_id`.',
    },
    {
      t: 'ex', id: 'm06-e2',
      prompt: "Pour chaque **année**, donne le D+ total (`dplus_total`, arrondi). Classe par année croissante.",
      starter: 'SELECT year, ROUND(SUM(dplus_m)) AS dplus_total\nFROM activities\nGROUP BY year\nORDER BY ...;',
      solution: 'SELECT year, ROUND(SUM(dplus_m)) AS dplus_total FROM activities GROUP BY year ORDER BY year;',
      ordered: true,
      hint: '`GROUP BY year` puis `ORDER BY year`.',
    },
    {
      t: 'ex', id: 'm06-e3',
      prompt: "Nombre de courses **par catégorie** (`categorie`), en ne gardant que les catégories comptant **au moins 2 courses**. Colonnes `categorie`, `nb`.",
      starter: 'SELECT categorie, COUNT(*) AS nb\nFROM races\nGROUP BY categorie\nHAVING ...;',
      solution: 'SELECT categorie, COUNT(*) AS nb FROM races GROUP BY categorie HAVING COUNT(*) >= 2;',
      hint: '`HAVING COUNT(*) >= 2`.',
    },
    {
      t: 'ex', id: 'm06-e4',
      prompt: "🏁 **Défi** : pour chaque année, calcule la **distance moyenne** par sortie (`dist_moy`, arrondie à 1 décimale) et n'affiche que les années où cette moyenne dépasse **12 km**. Trie par `dist_moy` décroissant.",
      starter: 'SELECT year, ROUND(AVG(distance_km), 1) AS dist_moy\nFROM activities\nGROUP BY year\nHAVING ...\nORDER BY ...;',
      solution: 'SELECT year, ROUND(AVG(distance_km), 1) AS dist_moy FROM activities GROUP BY year HAVING AVG(distance_km) > 12 ORDER BY dist_moy DESC;',
      ordered: true,
      hint: 'Regroupe par `year`, filtre les groupes avec `HAVING AVG(distance_km) > 12`, trie sur l\'alias `dist_moy DESC`.',
    },
  ],
};
