// Modules 07 → 10 : jointures, sous-requêtes, CTE, CASE/COALESCE.

export const M07 = {
  id: 'm07',
  navTitle: 'JOIN (jointures)',
  title: 'Module 7 — Les jointures (JOIN)',
  subtitle: 'Relier plusieurs tables pour combiner leurs informations.',
  blocks: [
    { t: 'h', text: 'Pourquoi joindre ?' },
    { t: 'p', text: "Tes données sont réparties dans plusieurs tables reliées par des **clés étrangères**. `activities.type_id` pointe vers `activity_types.id` ; `activities.race_id` pointe vers `races.id`. Une **jointure** rassemble ces tables pour lire, sur une même ligne, des colonnes venant de plusieurs sources." },
    { t: 'h', text: 'INNER JOIN' },
    { t: 'p', text: "`INNER JOIN` (ou simplement `JOIN`) associe les lignes de deux tables **quand la condition de liaison est vraie**. Les lignes sans correspondance sont exclues. On préfixe souvent les colonnes par un **alias de table** (`a`, `t`…) pour lever toute ambiguïté." },
    { t: 'code', caption: 'Afficher le NOM du type au lieu de son id.', sql: "SELECT a.date,\n       a.distance_km,\n       t.name AS type\nFROM activities AS a\nJOIN activity_types AS t ON a.type_id = t.id\nLIMIT 15;" },
    { t: 'p', text: "Lecture : « pour chaque activité `a`, va chercher dans `activity_types t` la ligne dont `t.id` égale `a.type_id`, et récupère `t.name` »." },
    { t: 'h', text: 'LEFT JOIN' },
    { t: 'p', text: "`LEFT JOIN` garde **toutes** les lignes de la table de gauche, même sans correspondance à droite : les colonnes de droite valent alors `NULL`. Parfait pour lister toutes les activités en marquant celles qui sont des courses (la plupart ont `race_id` NULL)." },
    { t: 'code', caption: 'Toutes les activités ; le nom de course apparaît seulement si c’en est une.', sql: "SELECT a.date,\n       a.distance_km,\n       r.name AS course\nFROM activities AS a\nLEFT JOIN races AS r ON a.race_id = r.id\nWHERE a.race_id IS NOT NULL\nLIMIT 15;" },
    { t: 'p', text: "Avec `INNER JOIN` sur `race_id`, on n'aurait gardé que les activités-courses. Avec `LEFT JOIN` on peut garder tout le monde ; ici on refiltre volontairement avec `WHERE`." },
    { t: 'h', text: 'Joindre par la date' },
    { t: 'p', text: "Une liaison n'est pas forcément un id : on peut joindre `activities.date` à `daily_metrics.date` pour enrichir une sortie avec la forme du jour (`ctl`, `hrv`…)." },
    { t: 'code', caption: 'Enrichir chaque sortie 2026 avec la forme du jour.', sql: "SELECT a.date,\n       a.distance_km,\n       m.ctl,\n       m.hrv\nFROM activities AS a\nJOIN daily_metrics AS m ON a.date = m.date\nWHERE a.year = 2026\nORDER BY a.date\nLIMIT 15;" },
    { t: 'tip', text: "L'ordre logique : `FROM ... JOIN ... ON ...` d'abord (construit la table combinée), **puis** `WHERE` filtre, puis le reste. Tu peux enchaîner plusieurs `JOIN` pour relier 3 tables ou plus." },
    { t: 'note', text: "`INNER JOIN`, `LEFT JOIN`, `ON` sont standard partout. Attention : MySQL ne connaît pas `FULL OUTER JOIN` (SQLite l'a depuis 3.39, PostgreSQL oui). `RIGHT JOIN` existe en PostgreSQL/MySQL et en SQLite récent, mais on l'écrit rarement : il suffit d'inverser les tables et d'utiliser `LEFT JOIN`." },
    {
      t: 'ex', id: 'm07-e1',
      prompt: "Affiche `date`, `distance_km` et le **nom du type** (`type`) pour 20 activités, en joignant `activities` et `activity_types`.",
      starter: "SELECT a.date, a.distance_km, t.name AS type\nFROM activities AS a\nJOIN activity_types AS t ON ...\nLIMIT 20;",
      solution: "SELECT a.date, a.distance_km, t.name AS type FROM activities AS a JOIN activity_types AS t ON a.type_id = t.id LIMIT 20;",
      hint: "La condition de liaison est `a.type_id = t.id`.",
    },
    {
      t: 'ex', id: 'm07-e2',
      prompt: "Pour chaque **activité qui est une course** (`race_id` non NULL), affiche `a.date`, `a.distance_km` (distance mesurée) et `r.name` (nom de la course).",
      starter: "SELECT a.date, a.distance_km, r.name\nFROM activities AS a\nJOIN races AS r ON ...;",
      solution: "SELECT a.date, a.distance_km, r.name FROM activities AS a JOIN races AS r ON a.race_id = r.id;",
      hint: "`JOIN races AS r ON a.race_id = r.id` — l'INNER JOIN élimine déjà les activités sans course.",
    },
    {
      t: 'ex', id: 'm07-e3',
      prompt: "🏁 **Défi** : associe chaque sortie de 2026 à sa forme du jour. Affiche `a.date`, `a.distance_km`, `m.fc_repos`, `m.hrv`, uniquement les jours où `m.hrv` est renseigné. Trie par date.",
      starter: "SELECT a.date, a.distance_km, m.fc_repos, m.hrv\nFROM activities AS a\nJOIN daily_metrics AS m ON ...\nWHERE ...\nORDER BY a.date;",
      solution: "SELECT a.date, a.distance_km, m.fc_repos, m.hrv FROM activities AS a JOIN daily_metrics AS m ON a.date = m.date WHERE a.year = 2026 AND m.hrv IS NOT NULL ORDER BY a.date;",
      ordered: true,
      hint: "Joins sur `a.date = m.date`, filtre `a.year = 2026 AND m.hrv IS NOT NULL`.",
    },
  ],
};

export const M08 = {
  id: 'm08',
  navTitle: 'Sous-requêtes',
  title: 'Module 8 — Les sous-requêtes',
  subtitle: 'Une requête à l’intérieur d’une autre pour répondre à des questions en deux temps.',
  blocks: [
    { t: 'h', text: "Qu'est-ce qu'une sous-requête ?" },
    { t: 'p', text: "Une **sous-requête** est une requête `SELECT` imbriquée dans une autre, entre parenthèses. On l'utilise quand une valeur du filtre dépend elle-même d'un calcul sur la base." },
    { t: 'h', text: 'Sous-requête scalaire (une seule valeur)' },
    { t: 'p', text: "Si la sous-requête renvoie **une seule valeur**, on peut la comparer directement. Exemple : les sorties plus longues que la moyenne générale." },
    { t: 'code', caption: 'Sorties au-dessus de la distance moyenne.', sql: "SELECT date, distance_km\nFROM activities\nWHERE distance_km > (SELECT AVG(distance_km) FROM activities)\nORDER BY distance_km DESC\nLIMIT 15;" },
    { t: 'p', text: "La sous-requête `(SELECT AVG(distance_km) FROM activities)` est calculée d'abord, renvoie un nombre, puis la requête externe l'utilise comme seuil." },
    { t: 'h', text: 'Sous-requête avec IN (une liste)' },
    { t: 'p', text: "Si la sous-requête renvoie **plusieurs valeurs** (une colonne), on la teste avec `IN`. Exemple : les activités qui ont eu lieu un jour de course." },
    { t: 'code', caption: 'Activités dont la date correspond à une date de course.', sql: "SELECT date, distance_km, dplus_m\nFROM activities\nWHERE date IN (SELECT date FROM races)\nORDER BY date;" },
    { t: 'h', text: 'EXISTS' },
    { t: 'p', text: "`EXISTS (sous-requête)` est vrai si la sous-requête renvoie au moins une ligne. La sous-requête est **corrélée** : elle référence la ligne courante de la requête externe." },
    { t: 'code', caption: 'Jours de métriques où une activité a eu lieu.', sql: "SELECT m.date, m.ctl, m.hrv\nFROM daily_metrics AS m\nWHERE EXISTS (\n  SELECT 1 FROM activities AS a WHERE a.date = m.date\n)\nAND m.date >= '2026-01-01'\nORDER BY m.date\nLIMIT 15;" },
    { t: 'tip', text: "Une sous-requête peut aussi apparaître dans le `FROM` (on parle de **table dérivée**) : `FROM (SELECT ... ) AS x`. On lui donne toujours un alias. C'est utile pour agréger un résultat déjà agrégé." },
    { t: 'note', text: "Sous-requêtes, `IN`, `EXISTS` sont standard dans les trois moteurs. Astuce de perf identique partout : `EXISTS` s'arrête à la première correspondance, souvent plus efficace que `IN` sur de gros volumes corrélés." },
    {
      t: 'ex', id: 'm08-e1',
      prompt: "Affiche les sorties dont le **D+ dépasse la moyenne** des D+ de toutes les activités. Colonnes `date`, `dplus_m`. Trie par `dplus_m` décroissant, limite 15.",
      starter: "SELECT date, dplus_m\nFROM activities\nWHERE dplus_m > (SELECT ... FROM activities)\nORDER BY dplus_m DESC\nLIMIT 15;",
      solution: "SELECT date, dplus_m FROM activities WHERE dplus_m > (SELECT AVG(dplus_m) FROM activities) ORDER BY dplus_m DESC LIMIT 15;",
      ordered: true,
      hint: "La sous-requête scalaire est `(SELECT AVG(dplus_m) FROM activities)`.",
    },
    {
      t: 'ex', id: 'm08-e2',
      prompt: "Affiche `date` et `distance_km` des activités ayant eu lieu **le même jour qu'une course terminée** (`finished = 1`). Utilise une sous-requête avec `IN`.",
      starter: "SELECT date, distance_km\nFROM activities\nWHERE date IN (SELECT date FROM races WHERE ...);",
      solution: "SELECT date, distance_km FROM activities WHERE date IN (SELECT date FROM races WHERE finished = 1);",
      hint: "La sous-requête `SELECT date FROM races WHERE finished = 1` fournit la liste des dates.",
    },
    {
      t: 'ex', id: 'm08-e3',
      prompt: "🏁 **Défi** : affiche la course (`name`, `distance_km`, `dplus_m`) ayant le **plus gros dénivelé** parmi toutes les courses, en filtrant avec une sous-requête `MAX`.",
      starter: "SELECT name, distance_km, dplus_m\nFROM races\nWHERE dplus_m = (SELECT ... FROM races);",
      solution: "SELECT name, distance_km, dplus_m FROM races WHERE dplus_m = (SELECT MAX(dplus_m) FROM races);",
      hint: "`WHERE dplus_m = (SELECT MAX(dplus_m) FROM races)`.",
    },
  ],
};

export const M09 = {
  id: 'm09',
  navTitle: 'CTE (WITH)',
  title: 'Module 9 — Les CTE (WITH)',
  subtitle: 'Nommer une étape intermédiaire pour écrire des requêtes lisibles par étapes.',
  blocks: [
    { t: 'h', text: 'Common Table Expression' },
    { t: 'p', text: "Une **CTE** (Common Table Expression), introduite par `WITH`, donne un **nom** à une sous-requête, placée *avant* la requête principale. On l'utilise ensuite comme une table. Résultat : des requêtes complexes lues **de haut en bas**, étape par étape, au lieu de sous-requêtes imbriquées difficiles à suivre." },
    { t: 'code', caption: 'Volume par année, puis on ne garde que les grosses années.', sql: "WITH volume_annuel AS (\n  SELECT year,\n         COUNT(*)               AS nb,\n         ROUND(SUM(distance_km)) AS km\n  FROM activities\n  GROUP BY year\n)\nSELECT *\nFROM volume_annuel\nWHERE km > 1500\nORDER BY km DESC;" },
    { t: 'p', text: "La CTE `volume_annuel` calcule le résumé par année ; la requête finale la filtre et la trie. On aurait pu le faire avec `HAVING`, mais la CTE devient précieuse dès que le calcul se complique." },
    { t: 'h', text: 'Enchaîner plusieurs CTE' },
    { t: 'p', text: "On peut définir plusieurs CTE séparées par des virgules ; chacune peut s'appuyer sur la précédente. Le raisonnement se lit comme une suite d'étapes." },
    { t: 'code', caption: 'Étape 1 : stats par type. Étape 2 : on lit joliment.', sql: "WITH par_type AS (\n  SELECT type_id,\n         COUNT(*)           AS nb,\n         ROUND(AVG(dplus_m)) AS dplus_moy\n  FROM activities\n  GROUP BY type_id\n)\nSELECT t.name AS type,\n       p.nb,\n       p.dplus_moy\nFROM par_type AS p\nJOIN activity_types AS t ON p.type_id = t.id\nORDER BY p.dplus_moy DESC;" },
    { t: 'tip', text: "Quand utiliser une CTE plutôt qu'une sous-requête ? Dès que la même sous-requête sert plusieurs fois, ou que l'imbrication nuit à la lisibilité. Le résultat est identique ; c'est un choix de **clarté**." },
    { t: 'note', text: "`WITH` est standard (SQL:1999) et supporté par SQLite (≥ 3.8.3), PostgreSQL et MySQL (≥ 8.0). Les **CTE récursives** (`WITH RECURSIVE`) existent aussi partout — utiles pour parcourir des hiérarchies ; hors périmètre de ce module d'intro." },
    {
      t: 'ex', id: 'm09-e1',
      prompt: "Avec une CTE nommée `par_annee` qui calcule le D+ total par année, affiche les années dont le D+ total dépasse **20000 m**. Colonnes `year`, `dplus_total`. Trie par `dplus_total` décroissant.",
      starter: "WITH par_annee AS (\n  SELECT year, ROUND(SUM(dplus_m)) AS dplus_total\n  FROM activities\n  GROUP BY year\n)\nSELECT * FROM par_annee\nWHERE ...\nORDER BY ...;",
      solution: "WITH par_annee AS (SELECT year, ROUND(SUM(dplus_m)) AS dplus_total FROM activities GROUP BY year) SELECT * FROM par_annee WHERE dplus_total > 20000 ORDER BY dplus_total DESC;",
      ordered: true,
      hint: "Filtre la CTE avec `WHERE dplus_total > 20000`, puis `ORDER BY dplus_total DESC`.",
    },
    {
      t: 'ex', id: 'm09-e2',
      prompt: "🏁 **Défi** : avec une CTE `stats_type` (nombre et distance moyenne par `type_id`), joins-la à `activity_types` pour afficher `type` (le nom), `nb`, `dist_moy` (arrondie à 1 décimale). Trie par `nb` décroissant.",
      starter: "WITH stats_type AS (\n  SELECT type_id, COUNT(*) AS nb, ROUND(AVG(distance_km), 1) AS dist_moy\n  FROM activities\n  GROUP BY type_id\n)\nSELECT t.name AS type, s.nb, s.dist_moy\nFROM stats_type AS s\nJOIN activity_types AS t ON ...\nORDER BY ...;",
      solution: "WITH stats_type AS (SELECT type_id, COUNT(*) AS nb, ROUND(AVG(distance_km), 1) AS dist_moy FROM activities GROUP BY type_id) SELECT t.name AS type, s.nb, s.dist_moy FROM stats_type AS s JOIN activity_types AS t ON s.type_id = t.id ORDER BY s.nb DESC;",
      ordered: true,
      hint: "Joins `s.type_id = t.id`, puis `ORDER BY s.nb DESC`.",
    },
  ],
};

export const M10 = {
  id: 'm10',
  navTitle: 'CASE & NULL',
  title: 'Module 10 — CASE, COALESCE, NULLIF',
  subtitle: 'Créer des catégories conditionnelles et gérer proprement les valeurs manquantes.',
  blocks: [
    { t: 'h', text: 'CASE : le « si… alors » du SQL' },
    { t: 'p', text: "`CASE` construit une valeur **conditionnelle**, colonne par colonne. Sa forme : `CASE WHEN condition THEN valeur ... ELSE valeur_par_defaut END`. Idéal pour classer chaque ligne dans une catégorie." },
    { t: 'code', caption: 'Étiqueter chaque sortie selon sa distance.', sql: "SELECT date,\n       distance_km,\n       CASE\n         WHEN distance_km >= 30 THEN 'longue'\n         WHEN distance_km >= 12 THEN 'moyenne'\n         ELSE 'courte'\n       END AS categorie\nFROM activities\nLIMIT 20;" },
    { t: 'p', text: "Les `WHEN` sont évalués **dans l'ordre** : la première condition vraie gagne. `ELSE` capte tout le reste (sans `ELSE`, une ligne non couverte reçoit `NULL`)." },
    { t: 'h', text: 'CASE combiné à une agrégation' },
    { t: 'p', text: "Astuce puissante : `SUM(CASE WHEN ... THEN 1 ELSE 0 END)` compte les lignes qui remplissent une condition. On peut faire plusieurs compteurs en une requête (« pivot »)." },
    { t: 'code', caption: 'Par année : combien de sorties courtes vs longues.', sql: "SELECT year,\n       SUM(CASE WHEN distance_km >= 30 THEN 1 ELSE 0 END) AS nb_longues,\n       SUM(CASE WHEN distance_km < 12 THEN 1 ELSE 0 END)  AS nb_courtes\nFROM activities\nGROUP BY year\nORDER BY year;" },
    { t: 'h', text: 'COALESCE : une valeur de repli' },
    { t: 'p', text: "`COALESCE(a, b, ...)` renvoie le **premier argument non NULL**. Parfait pour remplacer les FC manquantes par une valeur lisible ou une valeur par défaut." },
    { t: 'code', caption: "Afficher 0 quand la FC moyenne est absente.", sql: "SELECT date,\n       distance_km,\n       COALESCE(hr_moy, 0) AS fc\nFROM activities\nLIMIT 20;" },
    { t: 'h', text: 'NULLIF : produire un NULL' },
    { t: 'p', text: "`NULLIF(a, b)` renvoie `NULL` si `a = b`, sinon `a`. Usage classique : **éviter une division par zéro** en transformant le diviseur 0 en NULL (une division par NULL donne NULL, pas une erreur)." },
    { t: 'code', caption: 'Verticalité sûre, même si distance = 0.', sql: "SELECT date,\n       dplus_m,\n       distance_km,\n       ROUND(dplus_m / NULLIF(distance_km, 0), 1) AS d_par_km\nFROM activities\nLIMIT 20;" },
    { t: 'note', text: "`CASE`, `COALESCE`, `NULLIF` sont **standard** partout. MySQL a en plus `IFNULL(a,b)` (équivalent à `COALESCE` à deux arguments) et `IF(cond,a,b)` ; SQLite a `IFNULL` aussi, mais `COALESCE` est le choix portable à privilégier." },
    {
      t: 'ex', id: 'm10-e1',
      prompt: "Classe chaque **course** selon sa distance : `'ultra'` si `>= 100`, `'trail long'` si `>= 42`, sinon `'trail court'`, sous l'alias `format`. Colonnes `name`, `distance_km`, `format`.",
      starter: "SELECT name, distance_km,\n       CASE\n         WHEN ... THEN 'ultra'\n         WHEN ... THEN 'trail long'\n         ELSE 'trail court'\n       END AS format\nFROM races;",
      solution: "SELECT name, distance_km, CASE WHEN distance_km >= 100 THEN 'ultra' WHEN distance_km >= 42 THEN 'trail long' ELSE 'trail court' END AS format FROM races;",
      hint: "Ordre des `WHEN` du plus grand au plus petit seuil : `>= 100`, puis `>= 42`, puis `ELSE`.",
    },
    {
      t: 'ex', id: 'm10-e2',
      prompt: "Affiche `date`, `distance_km` et une colonne `fc_affichee` valant la FC moyenne, ou le texte `'n/d'` si elle est NULL. (Limite 20.)",
      starter: "SELECT date, distance_km, COALESCE(...) AS fc_affichee\nFROM activities\nLIMIT 20;",
      solution: "SELECT date, distance_km, COALESCE(hr_moy, 'n/d') AS fc_affichee FROM activities LIMIT 20;",
      hint: "`COALESCE(hr_moy, 'n/d')` : la première valeur non NULL gagne.",
    },
    {
      t: 'ex', id: 'm10-e3',
      prompt: "🏁 **Défi** : par année, compte les sorties **avec FC** (`hr_moy` non NULL) et **sans FC** en deux colonnes `avec_fc` et `sans_fc`, à l'aide de `SUM(CASE ...)`. Trie par année.",
      starter: "SELECT year,\n       SUM(CASE WHEN hr_moy IS NOT NULL THEN 1 ELSE 0 END) AS avec_fc,\n       SUM(CASE WHEN ... THEN 1 ELSE 0 END) AS sans_fc\nFROM activities\nGROUP BY year\nORDER BY year;",
      solution: "SELECT year, SUM(CASE WHEN hr_moy IS NOT NULL THEN 1 ELSE 0 END) AS avec_fc, SUM(CASE WHEN hr_moy IS NULL THEN 1 ELSE 0 END) AS sans_fc FROM activities GROUP BY year ORDER BY year;",
      ordered: true,
      hint: "Deux `SUM(CASE ...)`, l'un sur `hr_moy IS NOT NULL`, l'autre sur `hr_moy IS NULL`.",
    },
  ],
};
